version: "3.1"
services:
   nest-app:
      container_name: nest-app
      image: node:18.13.0
      user: node
      working_dir: '/app'
      volumes:
         - ./:/app
      ports:
         - 8080:8080
      command: 'yarn start:dev'