receivers:
  otlp:
    protocols:
      # grpc:
      http:
        cors:
          allowed_origins:
            - http://*
            - https://*

exporters:
  otlp:
   endpoint: tempo-prod-04-prod-us-east-0.grafana.net:443
   headers:
     authorization: Basic NzI0NTUyOmdsY19leUp2SWpvaU9UYzBNRGs0SWl3aWJpSTZJbk4wWVdOckxUYzNNalExTWkxb2JDMXlaV0ZrTFhCdll5MXNiMnRwSWl3aWF5STZJbGxVZURob1ZFWmpPRm93YlRaNlJHSm9PVGMzTWpnelppSXNJbTBpT25zaWNpSTZJbkJ5YjJRdGRYTXRaV0Z6ZEMwd0luMTk=

processors:
  batch:

service:
  pipelines:
    traces:
      receivers: [otlp]
      exporters: [otlp]
      processors: [batch]